version: '3.3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sawitpro'
      MYSQL_USER: 'sawidproadmin'
      MYSQL_PASSWORD: 'vaeiiGbL%j3jjQ!6duFKk79koKYLch%d'
      MYSQL_ROOT_PASSWORD: 'vaeiiGbL%j3jjQ!6duFKk79koKYLch%d'
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "6969:6969"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
